//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::bookmark::Entity as Bookmark;
pub use super::groups::Entity as Groups;
pub use super::organization::Entity as Organization;
pub use super::user::Entity as User;
pub use super::workspace::Entity as Workspace;
